### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by timholy** [twadleigh/jlcall#1]
I did think of one question: should this package end in `.jl`? I'm not clear on whether it will even contain any (non-C) julia code. Also, see https://github.com/JuliaLang/pyjulia and https://github.com/armgong/RJulia. Should it be MexJulia? (I quite like the Mex part of the name, that's very clear and better than MatJulia, in my opinion.)

**Comment by twadleigh** [comment]
Yeah, it will probably never be a proper julia package, so I'll drop the .jl.

I'll rename it mexjulia, which is what I called it in the first place when I started this.

**Comment by twadleigh** [comment]
Regarding Julia code: I'm hoping to do most of the heavy lifting w.r.t. marshaling on the Julia side, so there may end up being a decent amount of it in this project.

**Comment by timholy** [comment]
Ah, OK. Really any choice is fine with me.
