### ISSUE TITLE
Undefined references when compiling

### ISSUE THREAD

**Issue by jebej** [twadleigh/jlcall#14]
Note sure if it is related, but using the latest master the compiler cannot find `libjulia.dll.a`, even though `julia_lib_dir` seems to be defined properly. I instead pass the full path to the dll.a. The compilation then starts, but fails due to undefined references:

```
Error using mex
C:\Users\Jeremy\AppData\Local\Temp\mex_26021428342511_9972\jlcall.obj:jlcall.cpp:(.text+0xfd):
undefined reference to `__imp_jl_tls_states'
C:\Users\Jeremy\AppData\Local\Temp\mex_26021428342511_9972\jlcall.obj:jlcall.cpp:(.text+0x168):
undefined reference to `__imp_jl_tls_states'
C:\Users\Jeremy\AppData\Local\Temp\mex_26021428342511_9972\jlcall.obj:jlcall.cpp:(.text+0x1f6):
undefined reference to `__imp_jl_tls_states'
collect2.exe: error: ld returned 1 exit status
```

I am compiling with MinGW 4.9.2

**Comment by twadleigh** [comment]
Could you check out the new `rebranded` branch and see if you are still having this issue or any new issues? I just completed a major overhaul and am making myself available over the coming days to chase down residual or new issues.

Thanks.

**Comment by jebej** [comment]
This is what I get on latest master:

```
>> Jl.build
The path of the Julia executable is C:\Users\Jeremy\AppData\Local\Julia-0.5.0\bin\julia.exe
The path of the Julia configuration script is C:\Users\Jeremy\AppData\Local\Julia-0.5.0\share\julia\julia-config.jl
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Ensuring the MATLAB package is installed...
INFO: Nothing to be done
Ensuring the MATLAB package is on master...
INFO: Checking out MATLAB master...
INFO: Pulling MATLAB latest master...
INFO: No packages to install, update or remove
Is the boot file loadable without error?
Severe:
The program '[408] C:\Users\Jeremy\AppData\Local\Julia-0.5.0\bin\julia.exe: Native' has exited with code 1 (0x1).
Internal Error: A primary message table for module 77 was already registered with a differing collection of error messages.Error using Jl.build (line 116)
Assertion failed.
```

**Comment by twadleigh** [comment]
Hmm. That is not a Julia error that I have seen before. Not sure how to proceed. Looks like a stock download of Julia, no?

**Comment by twadleigh** [comment]
BTW, the initial error you reported was due to the old version not defining the right threading-related macro now required for 0.5 build process. Past that one now. This one is new.

**Comment by jebej** [comment]
Yes, it is a standard install from the website. It seems that the crash happens non-deterministically, and only because of the `find_library` call, not the dlopen (here there is a crash on the second function call):

```
julia> using MATLAB

julia> Libdl.find_library("libmex", [MATLAB.matlab_library_path])
"C:\\Program Files\\MATLAB\\R2016a\\bin\\win64\\libmex"

julia> Libdl.find_library("libmex", [MATLAB.matlab_library_path])
Internal Error: A primary message table for module 77 was already registered with a differing collection of error messages.Severe:
The program '[7968] C:\Users\Jeremy\AppData\Local\Julia-0.5.0\bin\julia.exe: Native' has exited with code 1 (0x1).
```

It seems to be a julia problem. In the meantime, I will just replace the call by assuming that the DLL is named libmex and concatenating the strings.

**Comment by twadleigh** [comment]
I hadn't seen this error before this, but my co-worker just ran into it herself, so I might have an opportunity to make progress on it.

**Comment by twadleigh** [comment]
OK. It turned out my coworker had two versions of `MATLAB.jl` on her system. When I got rid of one I was able to get things to work for her. I'm not yet sure what the long-term solution is, but could that be your situation, as well?

**Comment by twadleigh** [comment]
I've made fairly significant changes since this was reported. I'm going to close this. Please open new issues as you find them.
