### ISSUE TITLE
Error running jlconfig in MATLAB R2010a on Windows 7: "Assertion failed"

### ISSUE THREAD

**Issue by bezanetti** [twadleigh/jlcall#15]
Hello!

I'm getting this error while running jlconfig.

??? Error using ==> jlconfig at 46
Assertion failed.

**Comment by twadleigh** [comment]
I've just completed a major reworking of `jlcall` (now called `mexjulia`). It is available on the `rebranded` branch. Could you check it out and see if you still get this error. I'll be happy to work with you over the coming days to resolve this or any new issues that might arise.

Thanks.

**Comment by twadleigh** [comment]
Closing. Reopen if it is still an issue for you.
