### ISSUE TITLE
extract common functionality from MATLAB.jl into a separate package and depend on that

### ISSUE THREAD

**Issue by twadleigh** [twadleigh/jlcall#20]
Probably called `MxArrays` or `MxBase`.

**Comment by twadleigh** [comment]
As the marshaling code copied over from `MATLAB.jl` evolves, the common ground between it and `mexjulia` is shrinking. It may be a bit before we can assess to what extent this is still a useful thing to do.

**Comment by musm** [comment]
I think it would also be nice to just rely on `MATLAB` to take care of the functionality needed? Looking over some of the files in `mexjulia` it looks like you based them on an older fork of `MATLAB`, which had many issues with segfaulting.

**Comment by twadleigh** [comment]
@musm, I will check out the recent patches on `MATLAB.jl` and apply them. However, `mexjulia` currently relies on patches in the `mxarray` code that don't make sense in the `MATLAB.jl` context.

**Comment by twadleigh** [comment]
For instance, one very invasive change that had to be made for `mexjulia` was the elimination of the `own` field. In the `mexjulia` context, MATLAB deletes the memory for unused objects itself when the mex function returns. To let Julia participate at all in the memory management of `MxArray`s will require careful object tracking and proper scoping constructs. For now, it leaves it all to MATLAB.

**Comment by musm** [comment]
`MxArray( ..., false)` would disable the `own` and let you manage it without having Julia call a finalizer. 

https://github.com/JuliaInterop/MATLAB.jl/blob/master/src/mxarray.jl#L7

But perhaps that is not as sophisticated as you require.

**Comment by twadleigh** [comment]
The story gets more complicated, for instance, when you allow the user to make values persist across calls to `mexjulia` via `mexMakeArrayPersistent`. To make matters worse, `mexMakeArrayPersistent` makes values that can't be passed back to MATLAB (without a copy). Managing both scoped and persistent values in a user-friendly way will require a lot of machinery that doesn't apply to the `MATLAB.jl` context.

**Comment by agbondy** [comment]
Another big difference I notice is that while both MATLAB's and mexjulia's mxarray.jl defines a series of functions for handling MxArray objects, only the MATLAB module exports these functions. As a result, MATLAB.MxArray types have many methods defined for them. MxArrays.MxArray types have almost none, severely reducing the functionality. Maybe I'm missing something? In any case, this seems to be at the root of the issue I opened. By simply adding to the "export ..." line in the MxArrays module definition file, I can solve this.
