### ISSUE TITLE
Passing matlab functions to julia function

### ISSUE THREAD

**Issue by musm** [twadleigh/jlcall#25]
I would like to pass my matlab function to a julia function that takes a function as argument.
Is this possible?

**Comment by twadleigh** [comment]
Yes, with a little extra marshaling work. The `lm_test.m` example (and accompanying files) show an example of this.

**Comment by twadleigh** [comment]
In fact, I think it might make sense to add a more generic method for making `MxArray`s callable that does the default data marshaling, so that treating an `MxArray` as a function will "just work" in the obvious cases.

**Comment by twadleigh** [comment]
#27 makes this easier. See the (updated) `lmdif_test.m` for an example of passing a matlab function handle to julia as a callback.

**Comment by musm** [comment]
thanks for the example.

Now the example doesn't ever finish running on my PC (looks like it froze, but I get no error messages)
FYI: I do have Optim and Calculus installed.
