### ISSUE TITLE
Jl.eval with function definition crashes MATLAB

### ISSUE THREAD

**Issue by bermanmaxim** [twadleigh/jlcall#5]
Hello, `Jl.eval` exception handling does not work for me under ubuntu, a simple `Jl.eval('foobar')` crashes Matlab.

Moreover, executing
`Jl.eval('my_func(x) = 2*x');`
crashes Matlab on my machine, whereas making it return something with
`Jl.eval('my_func(x) = 2*x; 0');`
works as expected and defines my_func.

**Comment by twadleigh** [comment]
I'm not able to reproduce the first on my machine:

```
>> Jl.eval('foobar')
Error using jlcall
UndefVarError: foobar not defined

Error in Jl.eval (line 21)
          v1 = Jl.mex('mex_eval', e1);
```

but `Jl.eval('my_func(x) = 2*x');` will crash my machine. 

For the latter, I'm sure it's related to the fact that there doesn't exist a way to marshal a function (which is the value of the function definition expression) to MATLAB. That shouldn't crash matlab, though.

For the former, that's a bit of a head-scratcher for me. I'll open a separate issue for it.

**Comment by twadleigh** [comment]
Hmm. I'm now no longer able to duplicate the crash:

```
>> Jl.eval('my_func(x) = 2*x')
Error using jlcall
UndefVarError: name not defined

Error in Jl.eval (line 21)
          v1 = Jl.mex('mex_eval', e1);
```

**Comment by bermanmaxim** [comment]
@KristofferC , are you seeing these crashes on linux too ? As well as #6 ? Thanks

**Comment by bermanmaxim** [comment]
I added some "mexPrintf" in your code to see exactly where the crash was happening, and I found it to be at [line 48 of jlcall.cpp](https://github.com/twadleigh/jlcall/blob/3a5140ad5503cbb0b7aa27f40568d8e397e1fadc/src/jlcall.cpp#L48) at the `jl_call2` call...

**Comment by bermanmaxim** [comment]
Now if I replace `mex_showerror` in `boot.jl` by

```
function mex_showerror(e)
  println("here 1")
  buf = IOBuffer()
  println("here 2")
  showerror(buf, e)
  println("here 3")
  seek(buf, 0)
  println("here 4")
  ccall(mexfn(:mexErrMsgTxt), Void, (Ptr{Uint8},), readall(buf))
println("here 5")
end
```

I get

```
here 1
here 2
here 3
here 4
fish: “matlab&” terminated by signal SIGKILL (Forced quit)
```

so it is that ccall to `mexErrMsgTxt` that causes the crash...

**Comment by twadleigh** [comment]
Hmm. I would think that would be a pretty inocuous line. Maybe it's the string encoding. Could you try wrapping the `readall` in `ASCIIString`? _I.e._:

```
ccall(mexfn(:mexErrMsgTxt), Void, (Ptr{Uint8},), ASCIIString(readall(buf)))
```

**Comment by bermanmaxim** [comment]
That doesn't solve it.

**Comment by bermanmaxim** [comment]
See issue #6 for the fact that error reporting crashes my Matlab currently. Regarding this function definition, if I make the script output the error to the terminal, I get this error when I do `Jl.eval('f(x)=2*x')`:
`UndefVarError: name not defined`
However, I can check that the function has indeed be defined (`Jl.eval('f(2)')` returns 4).
Moreover, I still get a crash upon exiting MATLAB after defining this function like that:

```
*** Error in `/usr/local/MATLAB/R2014a/bin/glnxa64/MATLAB': double free or corruption (out): 0x00007f9f0ae92960 ***
fish: Job 2, “matlab&” terminated by signal SIGKILL (Forced quit)
```

while I don't get a crash from MATLAB upon exit after other errors (like `Jl.eval('foobar')`) or after a statement like `Jl.eval('f(x)=2; 0')`

**Comment by abhijithch** [comment]
I am having the same problem on windows 7 and MATLAB R2015b. Calling `Jl.eval` crashes MATLAB.

**Comment by twadleigh** [comment]
Closing this, as `mexjulia` has been tweaked significantly. However, I am still unable to get it running on Ubuntu, myself.
