### ISSUE TITLE
Jl.eval-ing an undefined symbol crashes MATLAB in Ubuntu

### ISSUE THREAD

**Issue by twadleigh** [twadleigh/jlcall#6]
In https://github.com/twadleigh/jlcall/issues/5#issue-110225788 @bermanmaxim reports:

> Hello, Jl.eval exception handling does not work for me under ubuntu, a simple Jl.eval('foobar') crashes Matlab.

However, in windows I get:

```
>> Jl.eval('foobar')
Error using jlcall
UndefVarError: foobar not defined

Error in Jl.eval (line 21)
          v1 = Jl.mex('mex_eval', e1);
```

as expected.

**Comment by bermanmaxim** [comment]
This is a more general issue: julia error reporting crashes MATLAB on Ubuntu.
If I comment out the call to `ccall` on error, and make the error output to the terminal instead, Matlab doesn't crash, it only complains that jlcall does not assign an output.

```
One or more output arguments not assigned during call to "jlcall".

Error in Jl.eval (line 21)
          v1 = Jl.mex('mex_eval', e1);
```

**Comment by twadleigh** [comment]
Closing this as stale.
